"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app/app-shell";
import { DataTable } from "@/components/app/data-table";
import { ErrorState } from "@/components/app/error-state";
import { LoadingState } from "@/components/app/loading-state";
import { StatusCard } from "@/components/app/status-card";
import { OrderTicket, type OrderTicketDraft } from "@/components/trading/order-ticket";
import { Button } from "@/components/ui/button";
import { getActiveBrokerSelection } from "@/lib/active-broker";
import { fetchWatchlist, formatPrice, formatTimestamp, getMarketStreamUrl, type MarketTick } from "@/lib/market-data";
import type { Exchange, Segment } from "@/lib/trading-api";
import { BellRing, Eye, Newspaper, TrendingUp } from "lucide-react";

export default function WatchlistPage() {
  const [ticks, setTicks] = useState<MarketTick[]>([]);
  const [streamStatus, setStreamStatus] = useState<"connecting" | "live" | "offline">("connecting");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [ticketDraft, setTicketDraft] = useState<OrderTicketDraft | null>(null);
  const [activeBrokerName, setActiveBrokerName] = useState("PAPER");

  useEffect(() => {
    const activeBroker = getActiveBrokerSelection();
    if (activeBroker?.display_name) {
      setActiveBrokerName(activeBroker.display_name);
    }
  }, []);

  useEffect(() => {
    let isMounted = true;

    async function loadWatchlist() {
      try {
        const data = await fetchWatchlist();
        if (isMounted) {
          setTicks(data);
        }
      } catch (error) {
        if (isMounted) {
          setErrorMessage(error instanceof Error ? error.message : "Unable to load watchlist.");
        }
      }
    }

    void loadWatchlist();

    const socket = new WebSocket(getMarketStreamUrl());
    socket.onopen = () => setStreamStatus("live");
    socket.onclose = () => setStreamStatus("offline");
    socket.onerror = () => setStreamStatus("offline");
    socket.onmessage = (event) => {
      const nextTicks = JSON.parse(event.data) as MarketTick[];
      setTicks(nextTicks);
      setStreamStatus("live");
    };

    return () => {
      isMounted = false;
      socket.close();
    };
  }, []);

  function ticketExchange(tick: MarketTick): Exchange {
    return tick.exchange === "NFO" || tick.exchange === "BFO" || tick.exchange === "BSE" ? tick.exchange : "NSE";
  }

  function ticketSegment(tick: MarketTick): Segment {
    return tick.exchange === "NFO" || tick.exchange === "BFO" ? "FNO" : "EQ";
  }

  function quickOrder(tick: MarketTick, side: "BUY" | "SELL") {
    setTicketDraft({
      symbol: tick.symbol,
      exchange: ticketExchange(tick),
      segment: ticketSegment(tick),
      side,
      price: side === "BUY" ? String(tick.ask) : String(tick.bid)
    });
  }

  const rows = useMemo(
    () =>
      ticks.map((tick) => ({
        ...tick,
        ltpDisplay: formatPrice(tick.ltp),
        bidDisplay: formatPrice(tick.bid),
        askDisplay: formatPrice(tick.ask),
        timestampDisplay: formatTimestamp(tick.timestamp)
      })),
    [ticks]
  );

  return (
    <AppShell title="Watchlist" description="Mock symbols, desk annotations, and price snapshots for paper workflows.">
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatusCard title="Tracked Symbols" value={String(ticks.length)} helper="Mock index and option symbols" tone="blue" icon={Eye} />
        <StatusCard title="Market Stream" value={streamStatus === "live" ? "Live mock" : "Reconnecting"} helper="WebSocket mock feed" tone={streamStatus === "live" ? "green" : "amber"} trend="steady" icon={TrendingUp} />
        <StatusCard title="Execution Broker" value={activeBrokerName} helper="Paper flow works without broker login" tone="amber" icon={Newspaper} />
        <StatusCard title="Open Interest" value={ticks.reduce((sum, tick) => sum + tick.oi, 0).toLocaleString("en-IN")} helper="Mock option and index OI" tone="blue" icon={BellRing} />
      </section>
      {errorMessage ? <ErrorState title="Market data unavailable" description={errorMessage} /> : null}
      {!errorMessage && rows.length === 0 ? <LoadingState title="Loading watchlist" description="Fetching mock market ticks." /> : null}
      <section className="grid gap-4 xl:grid-cols-[1.3fr_0.9fr]">
        <DataTable
          title="Symbol Watchlist"
          description="Paper-only market data generated by the mock service."
          rows={rows}
          columns={[
            { key: "symbol", header: "Symbol", render: (row) => <span className="font-semibold">{row.symbol}</span> },
            { key: "ltp", header: "LTP", align: "right", render: (row) => row.ltpDisplay },
            { key: "bid", header: "Bid", align: "right", render: (row) => row.bidDisplay },
            { key: "ask", header: "Ask", align: "right", render: (row) => row.askDisplay },
            { key: "volume", header: "Volume", align: "right", render: (row) => row.volume.toLocaleString("en-IN") },
            { key: "oi", header: "OI", align: "right", render: (row) => row.oi.toLocaleString("en-IN") },
            {
              key: "quickBuy",
              header: "Quick Buy",
              align: "center",
              render: (row) => (
                <Button size="sm" onClick={() => quickOrder(row, "BUY")}>
                  Buy
                </Button>
              )
            },
            {
              key: "quickSell",
              header: "Quick Sell",
              align: "center",
              render: (row) => (
                <Button size="sm" variant="danger" onClick={() => quickOrder(row, "SELL")}>
                  Sell
                </Button>
              )
            }
          ]}
        />
        <OrderTicket draft={ticketDraft} />
      </section>
    </AppShell>
  );
}
